### ISSUE TITLE
US12- list for topics

### ISSUE THREAD

**Issue by LukazMartin** [UB-ES-19/F2-Quora#66]
I created a list where the user can select one topic before adding a question.
I think a selectable object list is the most intuitive.
Also created one topic "None" if a user doesn't want to add a topic on the post. Maybe this isn't the best way to do it.

**Comment by LukazMartin** [comment]
Also should we limit the number of topics a user can add? Consider that the list of topics already is limited.

**Comment by jperacaula** [comment]
We have discussed this @marinavc  and I, and we said to make it mandatory to choose between 1 and 3 topics. What do you think? @LukazMartin @arnaugamez @lousmontabes

**Comment by jperacaula** [comment]
I have thought of this list of topics:

- Politics
- Humanities
- Life
- Science
- Technology
- Mathematics
- Sports
- Travel
- Entertainment
- Literature
- Business
- Art
- Healthcare
- Cooking
- Education
- News

I have took them from [here](https://www.quora.com/topic/Major-Topics/organize).

**Comment by marinavc** [comment]
I think the list of topics is correct. I would change what @LukazMartin set as a 'None' topic to be 'Other' to avoid problems in the future. I think choosing between 1-3 is correct

**Comment by jperacaula** [comment]
The final list of topics that I have used to create the frontend is:

-     Politics
-     Humanities
-     Life
-     Science
-     Technology
-     Mathematics
-     Sports
-     Travel
-     Entertainment
-     Literature
-     Business
-     Art
-     Healthcare
-     Cooking
-     Education
-     News
-     Nature
-     Other

**Comment by jperacaula** [comment]
The final list I have used is the following:

- Technology
- Mathematics
- Entertainment
- Politics
- Humanities
- Life
- Science
- Sports
- Travel
- Literature
- Business
- Art
- Healthcare
- Cooking
- Education
- News
- Nature
- Other
