### ISSUE TITLE
US8 - Search user by name

### ISSUE THREAD

**Issue by LukazMartin** [UB-ES-19/F2-Quora#68]
I created a function search(word) thats returns all the users that contains the searched word in the first_name or last_name or if they are exactly equal to the gmail. What do you think about this implementation?  Because if someone search "ma" and we return also the users which emails contains "ma" we will return nearly everyone (because of gMAil). We could also just take the part before the @ and look if this cointains the word.

**Comment by LukazMartin** [comment]
Maybe we should also order the users in order to most probably who was searched. (Looking if the word is exactly equal to first_name or looking how many followers one account has)

**Comment by marinavc** [comment]
I think we discussed making the search dynamic so maybe passing the whole list to template and then  filter the list there would be the best way. When I start working on that I'll tell you the options I find!
